language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - nohup java -Djava.library.path=./DynamoDBLocal_lib -jar dynamodb_local/DynamoDBLocal.jar --port 3000
  - composer self-update
  - composer install

script: phpunit
